apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: /subscriptions/c83d31e0-2b22-4dbe-9340-b522a54aed64/resourceGroups/panel_advisorsy/providers/Microsoft.Storage/storageAccounts/storepaneladvisorsy
    #volumeHandle: "panel_advisorsy#storepaneladvisorsy#sharepaneladvisorsy"  # Nombre correcto
    volumeAttributes:
      shareName: sharepaneladvisorsy  # Nombre correcto del recurso compartido
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile
  resources:
    requests:
      storage: 5Gi